### PR TITLE
changes in the test script to support Archlinux  and avoid hide errors. ...

### LINKED ISSUE #74: Fix test script
./test exits with error. 

```
 ~/code/fades   get_version  sh -x test
+ set -eu
+ '[' 0 -ne 0 ']'
+ TARGET='fades tests'
+ nosetests3 -v -s fades tests
test_comp_eq (tests.test_cache.ComparisonsTestCase) ... ok
test_comp_ge (tests.test_cache.ComparisonsTestCase) ... ok
(....)

----------------------------------------------------------------------
Ran 77 tests in 0.083s

OK
+ flake8 fades tests --max-line-length=99
++ python3 setup.py --long-description
++ rst2html
+ OUTPUT='test: line 19: rst2html: command not found'
 ✘  ~/code/fades   get_version  
```

### PR DESCRIPTION
**Pull request by gilgamezh**
...resolve #74

### CODE REVIEW

**Comment by facundobatista** [comment]
I see a spurious line:

```
$ ./test

OK!  88 tests, 0 failures, 0 errors in 0.1s
rst2html is /usr/bin/rst2html
```

**Comment by facundobatista** [comment]
The comparison line should be:

```
if type rst2html 2>&1 > /dev/null; then
```

**Comment by gilgamezh** [comment]
done!

**Comment by facundobatista** [comment]
Thanks!

**Pull request merged**
