### PR TITLE
update travis settings fixes #386

### LINKED ISSUE #386: Update travis for modern Pythons

### PR DESCRIPTION
**Pull request by gilgamezh**

### CODE REVIEW

**Comment by gilgamezh** [comment]
@facundobatista  i'm removing 3.5 from the tests.  do you think it's an issue?

**Comment by gilgamezh** [comment]
This PR will fix #386

**Comment by facundobatista** [comment]
Here you removed the "run coverage for the latest stable python revision" behaviour. Is there a reason for that?

**Comment by facundobatista** [comment]
I mean, don't we need that for the posterior `coveralls`?

**Comment by gilgamezh** [comment]
@facundobatista fixed! now coveralls is working only for 3.8

**Pull request merged**
