### PR TITLE
Parse requirements from a file. Fixes #58.

### LINKED ISSUE #58: Support requirements from a file
Like, with -r or --requirements

So, you can do (without commenting anything in foo.py):

```
    fades --requirements=req.txt foo.py
```
Or also to open in interactive mode with those dependencies:

```
    fades --interactive --requirements=req.txt 
```

### PR DESCRIPTION
**Pull request by facundobatista**

### CODE REVIEW

**Comment by gilgamezh** [comment]
is `--dependency` overwriting `--requirement` or is a bug?

**Comment by facundobatista** [comment]
It's a bug! it suppose to be merged , but actually as first key is the repo, it's overwritten

**Comment by facundobatista** [comment]
There I merged the dependencies using a tested function :)

**Comment by gilgamezh** [comment]
nice! :+1: 

```
 ~/code/fades   deps-from-file  bin/fades -v -d requests -r ../waliki/requirements.txt
*** fades ***  2015-05-13 10:07:38,454  fades              DEBUG    Running Python sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0) on 'linux'
*** fades ***  2015-05-13 10:07:38,454  fades              DEBUG    Starting fades v. 2.1
*** fades ***  2015-05-13 10:07:38,455  fades              DEBUG    Arguments: Namespace(child_options=[], child_program=None, dependency=['requests'], quiet=False, requirement='../waliki/requirements.txt', verbose=True, version=False)
*** fades ***  2015-05-13 10:07:38,455  fades              DEBUG    Dependencies from source file: {}
*** fades ***  2015-05-13 10:07:38,455  fades              DEBUG    Dependencies from requirements file: {'pypi': [Requirement.parse('django>=1.5.1'), Requirement.parse('wheel==0.24.0'), Requirement.parse('micawber>=0.3.0')]}
*** fades ***  2015-05-13 10:07:38,455  fades              DEBUG    Dependencies from parameters: {'pypi': [Requirement.parse('requests')]}
*** fades ***  2015-05-13 10:07:38,456  fades.cache        DEBUG    Using cache index: '/home/ndemarchi/.local/share/fades/venvs.idx'
*** fades ***  2015-05-13 10:07:38,456  fades.cache        DEBUG    Searching a venv for reqs: {'pypi': [Requirement.parse('django>=1.5.1'), Requirement.parse('wheel==0.24.0'), Requirement.parse('micawber>=0.3.0'), Requirement.parse('requests')]}
*** fades ***  2015-05-13 10:07:38,457  fades.cache        DEBUG    Found a matching venv! {'timestamp': 1431522452, 'metadata': {'pip_installed': True, 'env_bin_path': '/home/ndemarchi/.local/share/fades/b2496524-745b-447b-974c-9ab27e8c1f77/bin', 'env_path': '/home/ndemarchi/.local/share/fades/b2496524-745b-447b-974c-9ab27e8c1f77'}, 'installed': {'pypi': {'micawber': '0.3.2', 'wheel': '0.24.0', 'django': '1.8.1', 'requests': '2.7.0'}}}
*** fades ***  2015-05-13 10:07:38,457  fades              DEBUG    Calling the interactive Python interpreter
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

**Pull request merged**
